---
title: "Course Project - Practical Machine Learning"
author: "bthomas"
date: "April 20, 2016"
output: html_document
---
# Background
## Instructions

One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants.

## Review criterialess 
The goal of your project is to predict the manner in which they did the exercise. This is the "classe" variable in the training set. You may use any of the other variables to predict with. You should create a report describing how you built your model, how you used cross validation, what you think the expected out of sample error is, and why you made the choices you did. You will also use your prediction model to predict 20 different test cases.

## Peer Review Portion

Your submission for the Peer Review portion should consist of a link to a Github repo with your R markdown and compiled HTML file describing your analysis. Please constrain the text of the writeup to < 2000 words and the number of figures to be less than 5. It will make it easier for the graders if you submit a repo with a gh-pages branch so the HTML page can be viewed online (and you always want to make it easy on graders :-).
Course Project Prediction Quiz Portion

Apply your machine learning algorithm to the 20 test cases available in the test data above and submit your predictions in appropriate format to the Course Project Prediction Quiz for automated grading.
Reproducibility

Due to security concerns with the exchange of R code, your code will not be run during the evaluation by your classmates. Please be sure that if they download the repo, they will be able to view the compiled HTML version of your analysis.

## Research Question
Using attributes from belt, forearm, arm, and dumbell of the 6 Prediction Assignment Writeupless 

## Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).
Data

The training data for this project are available here: https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har. If you use the document you create for this class for any purpose please cite them as they have been very generous in allowing their data to be used for this kind of assignment.participants,


# Data Ingestion

```{r}
# Clean up environmnet
rm(list=ls())

library(RCurl)
library(caret)

# set working directory to the Github folder
setwd("~/Github/practical-machine-learning")

# check to see if the CSV files are in a data directory and if not download them
if (!file.exists("./Data/training.csv")) {
        training_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
        download.file(training_url, destfile = "./Data/training.csv", method = "libcurl")
}

if (!file.exists("./Data/test.csv")) {
        test_url <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
        download.file(test_url, destfile = "./Data/test.csv", method = "libcurl")
        
}

# build training dataset from attributes that contain belt, forearm, arm, and dumbell

training <- read.csv("./Data/training.csv", header = TRUE, na.strings=c("NA","NaN", " "))
# Use a regex to find features that are of interest
# Add user name back
training_cols <- grepl("arm|belt|dumbell|classe|user_name", names(training), ignore.case = TRUE)
# Remove columns not of interest
training <- training[training_cols]
colnames_train <- colnames(training)

# get test dataset
testing <- read.csv("./Data/test.csv", header = TRUE, na.strings=c("NA","NaN", " "))
testing_cols <- grepl("arm|belt|dumbell|classe", names(training), ignore.case = TRUE)
testing <- testing[training_cols]

# remove columns that are blank or DIV/0!
# Count the number of non-NAs in each col.
nonNAs <- function(x) {
        as.vector(apply(x, 2, function(x) length(which(!is.na(x)))))
}

# Build vector of missing data or NA columns to drop.
colcnts <- nonNAs(training)
drops <- c()
for (cnt in 1:length(colcnts)) {
        if (colcnts[cnt] < nrow(training)) {
                drops <- c(drops, colnames_train[cnt])
        }
}

# Drop NA data
training <- training[,!(names(training) %in% drops)]
training <- training[,1:length(colnames(training))]

testing <- testing[,!(names(testing) %in% drops)]
testing <- testing[,1:length(colnames(testing))]

# Show remaining columns.
colnames(training)

# Confirm attributes between training and test are identical
colnames_train <- names(training)
colnames_test <- names(testing)
all.equal(colnames_train[1:length(colnames_train)-1], colnames_test[1:length(colnames_train)-1])

# Need to check for nzv and blank columns

```

